OBJDIR = test
dummy_build_folder := $(shell mkdir -p $(OBJDIR))

CFLAGS  += -DDEBUG -g -pthread -I. -D_FILE_OFFSET_BITS=64 -Wall
OFLAGS  = -O0

all: $(OBJDIR)/test

.SILENT:
	
$(OBJDIR)/%.o: %.c
	echo "  CC    $<"
	$(CC) $(CFLAGS) $(OFLAGS) -c $< -o $@

$(OBJDIR)/test: sb_test.c $(OBJS)
	echo   "  CC    tests"
	$(CC) $(CFLAGS) $(OFLAGS) sb_test.c -lm -o $@ $(OBJS)
