OBJDIR = tests
dummy_build_folder := $(shell mkdir -p $(OBJDIR))

CFLAGS  += -I. -Wall
OFLAGS  = -O0

OBJS= $(OBJDIR)/cb_main_argp.o



all: $(OBJDIR)/tests

.SILENT:
	
$(OBJDIR)/%.o: %.c
	echo "  CC    $<"
	$(CC) $(CFLAGS) $(OFLAGS) -c $< -o $@

$(OBJDIR)/tests: cb_tests.c $(OBJS)
	echo   "  CC    tests"
	$(CC) $(CFLAGS) $(OFLAGS) cb_tests.c -lm -o $@ $(OBJS)