tests:
	make -f makefile.test

debug:
	make -f makefile.debug

rel:
	make -f makefile.release

clean-test:
	rm test/*.o
	rm test/tests

clean-debug:
	rm debug/*.o
	rm debug/minib

clean-rel:
	rm release/*.o
	rm release/minib